//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./gigapaxos/src/edu/umass/cs/gigapaxos/paxospackets/AcceptReplyPacket.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket")
#ifdef RESTRICT_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket
#define INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket 0
#else
#define INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket 1
#endif
#undef RESTRICT_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket

#if !defined (EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_) && (INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket || defined(INCLUDE_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket))
#define EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_

#define RESTRICT_EduUmassCsGigapaxosPaxospacketsPaxosPacket 1
#define INCLUDE_EduUmassCsGigapaxosPaxospacketsPaxosPacket 1
#include "edu/umass/cs/gigapaxos/paxospackets/PaxosPacket.h"

@class EduUmassCsGigapaxosPaxosutilBallot;
@class IOSObjectArray;
@class JavaNioByteBuffer;
@class NetMinidevJsonJSONObject;
@class OrgJsonJSONObject;

@interface EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket : EduUmassCsGigapaxosPaxospacketsPaxosPacket {
 @public
  jint acceptor_;
  EduUmassCsGigapaxosPaxosutilBallot *ballot_;
  jint slotNumber_;
  jint maxCheckpointedSlot_;
  jlong requestID_;
}

#pragma mark Public

- (instancetype)initWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf;

- (instancetype)initWithInt:(jint)nodeID
withEduUmassCsGigapaxosPaxosutilBallot:(EduUmassCsGigapaxosPaxosutilBallot *)ballot
                    withInt:(jint)slotNumber
                    withInt:(jint)maxCheckpointedSlot;

- (instancetype)initWithInt:(jint)nodeID
withEduUmassCsGigapaxosPaxosutilBallot:(EduUmassCsGigapaxosPaxosutilBallot *)ballot
                    withInt:(jint)slotNumber
                    withInt:(jint)maxCheckpointedSlot
                   withLong:(jlong)requestID;

- (instancetype)initWithInt:(jint)nodeID
withEduUmassCsGigapaxosPaxosutilBallot:(EduUmassCsGigapaxosPaxosutilBallot *)ballot
                    withInt:(jint)slotNumber
                    withInt:(jint)maxCheckpointedSlot
                   withLong:(jlong)requestID
withEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket:(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *)ar;

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)jsonObject;

- (jlong)getRequestID;

- (jboolean)isCoalescable;

- (jboolean)isUndigestRequest;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

- (EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *)setDigestRequest;

- (JavaNioByteBuffer *)toBytesWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf;

- (OrgJsonJSONObject *)toJSONObjectImpl;

- (NetMinidevJsonJSONObject *)toJSONSmartImpl;

#pragma mark Protected

- (NSString *)getSummaryString;

@end

J2OBJC_STATIC_INIT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket)

J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket, ballot_, EduUmassCsGigapaxosPaxosutilBallot *)

inline jint EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_get_SIZEOF_ACCEPTREPLY();
#define EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_SIZEOF_ACCEPTREPLY 29
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket, SIZEOF_ACCEPTREPLY, jint)

inline jint EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_get_SIZEOF_BATCHEDACCEPTREPLY();
#define EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_SIZEOF_BATCHEDACCEPTREPLY 29
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket, SIZEOF_BATCHEDACCEPTREPLY, jint)

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_withLong_withEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *self, jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot, jlong requestID, EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *ar);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *new_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_withLong_withEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_(jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot, jlong requestID, EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *ar) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *create_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_withLong_withEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_(jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot, jlong requestID, EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *ar);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *self, jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *new_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_(jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *create_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_(jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_withLong_(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *self, jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot, jlong requestID);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *new_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_withLong_(jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot, jlong requestID) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *create_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithInt_withEduUmassCsGigapaxosPaxosutilBallot_withInt_withInt_withLong_(jint nodeID, EduUmassCsGigapaxosPaxosutilBallot *ballot, jint slotNumber, jint maxCheckpointedSlot, jlong requestID);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithOrgJsonJSONObject_(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *self, OrgJsonJSONObject *jsonObject);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *new_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithOrgJsonJSONObject_(OrgJsonJSONObject *jsonObject) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *create_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithOrgJsonJSONObject_(OrgJsonJSONObject *jsonObject);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithJavaNioByteBuffer_(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *self, JavaNioByteBuffer *bbuf);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *new_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithJavaNioByteBuffer_(JavaNioByteBuffer *bbuf) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *create_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_initWithJavaNioByteBuffer_(JavaNioByteBuffer *bbuf);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket)

#endif

#if !defined (EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_) && (INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket || defined(INCLUDE_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields))
#define EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_EduUmassCsGigapaxosPaxospacketsPaxosPacket 1
#define INCLUDE_EduUmassCsGigapaxosPaxospacketsPaxosPacket_GetType 1
#include "edu/umass/cs/gigapaxos/paxospackets/PaxosPacket.h"

@class IOSClass;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_Enum) {
  EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_Enum_acceptor = 0,
  EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_Enum_ballot = 1,
  EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_Enum_slotNumber = 2,
  EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_Enum_maxCheckpointedSlot = 3,
  EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_Enum_requestID = 4,
  EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_Enum_undigestRequest = 5,
};

@interface EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields : JavaLangEnum < NSCopying, EduUmassCsGigapaxosPaxospacketsPaxosPacket_GetType > {
 @public
  IOSClass *type_;
}

#pragma mark Public

- (IOSClass *)getType;

+ (EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_values_[];

inline EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_get_acceptor();
J2OBJC_ENUM_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields, acceptor)

inline EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_get_ballot();
J2OBJC_ENUM_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields, ballot)

inline EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_get_slotNumber();
J2OBJC_ENUM_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields, slotNumber)

inline EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_get_maxCheckpointedSlot();
J2OBJC_ENUM_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields, maxCheckpointedSlot)

inline EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_get_requestID();
J2OBJC_ENUM_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields, requestID)

inline EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_get_undigestRequest();
J2OBJC_ENUM_CONSTANT(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields, undigestRequest)

J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields, type_, IOSClass *)

FOUNDATION_EXPORT IOSObjectArray *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_values();

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields *EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket")
