//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./gigapaxos/src/edu/umass/cs/gigapaxos/paxospackets/BatchedAcceptReply.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply")
#ifdef RESTRICT_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply
#define INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply 0
#else
#define INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply 1
#endif
#undef RESTRICT_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply

#if !defined (EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_) && (INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply || defined(INCLUDE_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply))
#define EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_

#define RESTRICT_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket 1
#define INCLUDE_EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket 1
#include "edu/umass/cs/gigapaxos/paxospackets/AcceptReplyPacket.h"

#define RESTRICT_EduUmassCsNioInterfacesByteable 1
#define INCLUDE_EduUmassCsNioInterfacesByteable 1
#include "edu/umass/cs/nio/interfaces/Byteable.h"

@class IOSByteArray;
@class IOSObjectArray;
@class JavaLangLong;
@class JavaNioByteBuffer;
@class NetMinidevJsonJSONObject;
@class OrgJsonJSONObject;

@interface EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply : EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket < EduUmassCsNioInterfacesByteable >

#pragma mark Public

- (instancetype)initWithEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket:(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *)ar;

- (instancetype)initWithJavaNioByteBuffer:(JavaNioByteBuffer *)bbuf;

- (instancetype)initWithOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (jboolean)addAcceptReplyWithEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket:(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *)ar;

- (IOSObjectArray *)getAcceptedSlots;

- (JavaLangLong *)getRequestIDWithInt:(jint)slot;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

- (jint)size;

- (IOSByteArray *)toBytes;

- (OrgJsonJSONObject *)toJSONObjectImpl;

- (NetMinidevJsonJSONObject *)toJSONSmartImpl;

#pragma mark Protected

- (NSString *)getSummaryString;

@end

J2OBJC_STATIC_INIT(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply)

inline jint EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_get_MAX_BATCH_SIZE();
#define EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_MAX_BATCH_SIZE 2048
J2OBJC_STATIC_FIELD_CONSTANT(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply, MAX_BATCH_SIZE, jint)

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *self, EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *ar);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *new_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *ar) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *create_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithEduUmassCsGigapaxosPaxospacketsAcceptReplyPacket_(EduUmassCsGigapaxosPaxospacketsAcceptReplyPacket *ar);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithOrgJsonJSONObject_(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *self, OrgJsonJSONObject *json);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *new_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *create_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithOrgJsonJSONObject_(OrgJsonJSONObject *json);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithJavaNioByteBuffer_(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *self, JavaNioByteBuffer *bbuf);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *new_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithJavaNioByteBuffer_(JavaNioByteBuffer *bbuf) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply *create_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_initWithJavaNioByteBuffer_(JavaNioByteBuffer *bbuf);

FOUNDATION_EXPORT void EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply)

#endif

#if !defined (EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_) && (INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply || defined(INCLUDE_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields))
#define EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_EduUmassCsGigapaxosPaxospacketsPaxosPacket 1
#define INCLUDE_EduUmassCsGigapaxosPaxospacketsPaxosPacket_GetType 1
#include "edu/umass/cs/gigapaxos/paxospackets/PaxosPacket.h"

@class IOSClass;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_Enum) {
  EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_Enum_slots = 0,
};

@interface EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields : JavaLangEnum < NSCopying, EduUmassCsGigapaxosPaxospacketsPaxosPacket_GetType > {
 @public
  IOSClass *type_;
}

#pragma mark Public

- (IOSClass *)getType;

+ (EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields *EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_values_[];

inline EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields *EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_get_slots();
J2OBJC_ENUM_CONSTANT(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields, slots)

J2OBJC_FIELD_SETTER(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields, type_, IOSClass *)

FOUNDATION_EXPORT IOSObjectArray *EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_values();

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields *EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields *EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGigapaxosPaxospacketsBatchedAcceptReply")
