//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsclient/client/CryptoUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsclientClientCryptoUtils")
#ifdef RESTRICT_EduUmassCsGnsclientClientCryptoUtils
#define INCLUDE_ALL_EduUmassCsGnsclientClientCryptoUtils 0
#else
#define INCLUDE_ALL_EduUmassCsGnsclientClientCryptoUtils 1
#endif
#undef RESTRICT_EduUmassCsGnsclientClientCryptoUtils

#if !defined (EduUmassCsGnsclientClientCryptoUtils_) && (INCLUDE_ALL_EduUmassCsGnsclientClientCryptoUtils || defined(INCLUDE_EduUmassCsGnsclientClientCryptoUtils))
#define EduUmassCsGnsclientClientCryptoUtils_

@class EduUmassCsGnsclientClientUtilGuidEntry;

@interface EduUmassCsGnsclientClientCryptoUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)signDigestOfMessageWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guidEntry
                                                               withNSString:(NSString *)message;

+ (NSString *)signDigestOfMessageSecretKeyWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guidEntry
                                                                        withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsclientClientCryptoUtils)

FOUNDATION_EXPORT void EduUmassCsGnsclientClientCryptoUtils_init(EduUmassCsGnsclientClientCryptoUtils *self);

FOUNDATION_EXPORT EduUmassCsGnsclientClientCryptoUtils *new_EduUmassCsGnsclientClientCryptoUtils_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsclientClientCryptoUtils *create_EduUmassCsGnsclientClientCryptoUtils_init();

FOUNDATION_EXPORT NSString *EduUmassCsGnsclientClientCryptoUtils_signDigestOfMessageWithEduUmassCsGnsclientClientUtilGuidEntry_withNSString_(EduUmassCsGnsclientClientUtilGuidEntry *guidEntry, NSString *message);

FOUNDATION_EXPORT NSString *EduUmassCsGnsclientClientCryptoUtils_signDigestOfMessageSecretKeyWithEduUmassCsGnsclientClientUtilGuidEntry_withNSString_(EduUmassCsGnsclientClientUtilGuidEntry *guidEntry, NSString *message);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsclientClientCryptoUtils)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsclientClientCryptoUtils")
