//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsclient/client/GNSClientCommands.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsclientClientGNSClientCommands")
#ifdef RESTRICT_EduUmassCsGnsclientClientGNSClientCommands
#define INCLUDE_ALL_EduUmassCsGnsclientClientGNSClientCommands 0
#else
#define INCLUDE_ALL_EduUmassCsGnsclientClientGNSClientCommands 1
#endif
#undef RESTRICT_EduUmassCsGnsclientClientGNSClientCommands

#if !defined (EduUmassCsGnsclientClientGNSClientCommands_) && (INCLUDE_ALL_EduUmassCsGnsclientClientGNSClientCommands || defined(INCLUDE_EduUmassCsGnsclientClientGNSClientCommands))
#define EduUmassCsGnsclientClientGNSClientCommands_

#define RESTRICT_EduUmassCsGnsclientClientGNSClient 1
#define INCLUDE_EduUmassCsGnsclientClientGNSClient 1
#include "edu/umass/cs/gnsclient/client/GNSClient.h"

@class EduUmassCsGnsclientClientUtilGuidEntry;
@class EduUmassCsGnscommonAclAccessType;
@class IOSByteArray;
@class JavaLangDouble;
@class JavaNetInetSocketAddress;
@class JavaUtilArrayList;
@class OrgJsonJSONArray;
@class OrgJsonJSONObject;
@protocol JavaSecurityPublicKey;
@protocol JavaUtilSet;

@interface EduUmassCsGnsclientClientGNSClientCommands : EduUmassCsGnsclientClientGNSClient

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaNetInetSocketAddress:(JavaNetInetSocketAddress *)anyReconfigurator;

- (EduUmassCsGnsclientClientUtilGuidEntry *)accountGuidCreateWithNSString:(NSString *)alias
                                                             withNSString:(NSString *)password;

- (EduUmassCsGnsclientClientUtilGuidEntry *)accountGuidCreateSecureWithNSString:(NSString *)alias
                                                                   withNSString:(NSString *)password;

- (void)accountGuidRemoveWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (void)accountGuidRemoveSecureWithNSString:(NSString *)name;

- (void)accountGuidRemoveWithPasswordWithNSString:(NSString *)name
                                     withNSString:(NSString *)password;

- (NSString *)accountGuidVerifyWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                             withNSString:(NSString *)code;

- (NSString *)accountResendAuthenticationEmailWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (void)aclAddWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
        withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                      withNSString:(NSString *)field
                                      withNSString:(NSString *)accesserGuid;

- (void)aclAddSecureWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                                            withNSString:(NSString *)targetGuid
                                            withNSString:(NSString *)field
                                            withNSString:(NSString *)accesserGuid;

- (OrgJsonJSONArray *)aclGetWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                      withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                    withNSString:(NSString *)field
                                                    withNSString:(NSString *)readerGuid;

- (OrgJsonJSONArray *)aclGetSecureWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                                                          withNSString:(NSString *)targetGuid
                                                          withNSString:(NSString *)field;

- (void)aclRemoveWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
           withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                         withNSString:(NSString *)field
                                         withNSString:(NSString *)accesserGuid;

- (void)aclRemoveSecureWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                                               withNSString:(NSString *)targetGuid
                                               withNSString:(NSString *)field
                                               withNSString:(NSString *)accesserGuid;

- (void)activeCodeClearWithNSString:(NSString *)guid
                       withNSString:(NSString *)action
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writerGuid;

- (NSString *)activeCodeGetWithNSString:(NSString *)guid
                           withNSString:(NSString *)action
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)readerGuid;

- (void)activeCodeSetWithNSString:(NSString *)guid
                     withNSString:(NSString *)action
                    withByteArray:(IOSByteArray *)code
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writerGuid;

- (void)addAliasWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                              withNSString:(NSString *)name;

- (void)close;

- (NSString *)dump;

- (jboolean)fieldAclExistsWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                    withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                  withNSString:(NSString *)field;

- (jboolean)fieldAclExistsWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                    withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                  withNSString:(NSString *)field
                                                  withNSString:(NSString *)readerGuid;

- (void)fieldAppendWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                 withNSString:(NSString *)field
                                                 withNSString:(NSString *)value;

- (void)fieldAppendWithNSString:(NSString *)targetGuid
                   withNSString:(NSString *)field
           withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendWithNSString:(NSString *)targetGuid
                   withNSString:(NSString *)field
                   withNSString:(NSString *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendOrCreateWithNSString:(NSString *)targetGuid
                           withNSString:(NSString *)field
                           withNSString:(NSString *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendOrCreateListWithNSString:(NSString *)targetGuid
                               withNSString:(NSString *)field
                       withOrgJsonJSONArray:(OrgJsonJSONArray *)value
 withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendWithSetSemanticsWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                                 withNSString:(NSString *)field
                                                         withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (void)fieldAppendWithSetSemanticsWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                                 withNSString:(NSString *)field
                                                                 withNSString:(NSString *)value;

- (void)fieldAppendWithSetSemanticsWithNSString:(NSString *)targetGuid
                                   withNSString:(NSString *)field
                           withOrgJsonJSONArray:(OrgJsonJSONArray *)value
     withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendWithSetSemanticsWithNSString:(NSString *)targetGuid
                                   withNSString:(NSString *)field
                                   withNSString:(NSString *)value
     withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldClearWithNSString:(NSString *)targetGuid
                  withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldClearWithNSString:(NSString *)targetGuid
                  withNSString:(NSString *)field
          withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldCreateAclWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                              withNSString:(NSString *)field;

- (void)fieldCreateAclWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                              withNSString:(NSString *)field
                                              withNSString:(NSString *)writerGuid;

- (void)fieldCreateIndexWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                      withNSString:(NSString *)field
                                                      withNSString:(NSString *)index;

- (void)fieldCreateListWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                     withNSString:(NSString *)field
                                             withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (void)fieldCreateListWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
               withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldCreateOneElementListWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                               withNSString:(NSString *)field
                                                               withNSString:(NSString *)value;

- (void)fieldCreateOneElementListWithNSString:(NSString *)targetGuid
                                 withNSString:(NSString *)field
                                 withNSString:(NSString *)value
   withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldDeleteAclWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                              withNSString:(NSString *)field;

- (void)fieldDeleteAclWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                              withNSString:(NSString *)field
                                              withNSString:(NSString *)writerGuid;

- (jboolean)fieldExistsWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                     withNSString:(NSString *)field;

- (jboolean)fieldExistsWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (NSString *)fieldReadWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                            withJavaUtilArrayList:(JavaUtilArrayList *)fields;

- (NSString *)fieldReadWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                     withNSString:(NSString *)field;

- (NSString *)fieldReadWithNSString:(NSString *)targetGuid
              withJavaUtilArrayList:(JavaUtilArrayList *)fields
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (NSString *)fieldReadWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (OrgJsonJSONArray *)fieldReadArrayWithNSString:(NSString *)guid
                                    withNSString:(NSString *)field
      withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (NSString *)fieldReadArrayFirstElementWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                                      withNSString:(NSString *)field;

- (NSString *)fieldReadArrayFirstElementWithNSString:(NSString *)guid
                                        withNSString:(NSString *)field
          withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (void)fieldRemoveWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                 withNSString:(NSString *)field;

- (void)fieldRemoveWithNSString:(NSString *)targetGuid
                   withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                  withNSString:(NSString *)field
                                          withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (void)fieldReplaceWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                  withNSString:(NSString *)field
                                                  withNSString:(NSString *)value;

- (void)fieldReplaceWithNSString:(NSString *)targetGuid
                    withNSString:(NSString *)field
                    withNSString:(NSString *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceFirstElementWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                              withNSString:(NSString *)field
                                                              withNSString:(NSString *)value;

- (void)fieldReplaceFirstElementWithNSString:(NSString *)targetGuid
                                withNSString:(NSString *)field
                                withNSString:(NSString *)value
  withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceListWithNSString:(NSString *)targetGuid
                        withNSString:(NSString *)field
                withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceOrCreateWithNSString:(NSString *)targetGuid
                            withNSString:(NSString *)field
                            withNSString:(NSString *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceOrCreateListWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                              withNSString:(NSString *)field
                                                      withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (void)fieldReplaceOrCreateListWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                              withNSString:(NSString *)field
                                                              withNSString:(NSString *)value;

- (void)fieldReplaceOrCreateListWithNSString:(NSString *)targetGuid
                                withNSString:(NSString *)field
                        withOrgJsonJSONArray:(OrgJsonJSONArray *)value
  withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSetElementWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
                       withNSString:(NSString *)newValue
                            withInt:(jint)index
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSetNullWithNSString:(NSString *)targetGuid
                    withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSubstituteWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                     withNSString:(NSString *)field
                                             withOrgJsonJSONArray:(OrgJsonJSONArray *)newValue
                                             withOrgJsonJSONArray:(OrgJsonJSONArray *)oldValue;

- (void)fieldSubstituteWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)target
                                                     withNSString:(NSString *)field
                                                     withNSString:(NSString *)newValue
                                                     withNSString:(NSString *)oldValue;

- (void)fieldSubstituteWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
               withOrgJsonJSONArray:(OrgJsonJSONArray *)newValue
               withOrgJsonJSONArray:(OrgJsonJSONArray *)oldValue
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSubstituteWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
                       withNSString:(NSString *)newValue
                       withNSString:(NSString *)oldValue
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldUpdateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                 withNSString:(NSString *)field
                                                       withId:(id)value;

- (void)fieldUpdateWithNSString:(NSString *)targetGuid
                   withNSString:(NSString *)field
                         withId:(id)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (OrgJsonJSONArray *)getAliasesWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (OrgJsonJSONArray *)getLocationWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (OrgJsonJSONArray *)getLocationWithNSString:(NSString *)targetGuid
   withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)readerGuid;

- (void)groupAddGuidWithNSString:(NSString *)groupGuid
                    withNSString:(NSString *)guidToAdd
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupAddGuidsWithNSString:(NSString *)groupGuid
             withOrgJsonJSONArray:(OrgJsonJSONArray *)members
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupAddMembershipReadPermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                      withNSString:(NSString *)guidToAuthorize;

- (void)groupAddMembershipUpdatePermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                        withNSString:(NSString *)guidToAuthorize;

- (OrgJsonJSONArray *)groupGetMembersWithNSString:(NSString *)groupGuid
       withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (void)groupRemoveGuidWithNSString:(NSString *)groupGuid
                       withNSString:(NSString *)guidToRemove
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupRemoveGuidsWithNSString:(NSString *)groupGuid
                withOrgJsonJSONArray:(OrgJsonJSONArray *)members
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupRemoveMembershipReadPermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                         withNSString:(NSString *)guidToUnauthorize;

- (void)groupRemoveMembershipUpdatePermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                           withNSString:(NSString *)guidToUnauthorize;

- (void)guidBatchCreateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                  withJavaUtilSet:(id<JavaUtilSet>)aliases;

- (void)guidBatchCreateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                  withJavaUtilSet:(id<JavaUtilSet>)aliases
                                                         withLong:(jlong)timeout;

- (EduUmassCsGnsclientClientUtilGuidEntry *)guidCreateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                                                    withNSString:(NSString *)alias;

- (OrgJsonJSONArray *)guidGetGroupsWithNSString:(NSString *)guid
     withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (void)guidRemoveWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (void)guidRemoveWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                withNSString:(NSString *)guidToRemove;

- (OrgJsonJSONObject *)lookupAccountRecordWithNSString:(NSString *)accountGuid;

- (NSString *)lookupGuidWithNSString:(NSString *)alias;

- (OrgJsonJSONObject *)lookupGuidRecordWithNSString:(NSString *)guid;

- (NSString *)lookupPrimaryGuidWithNSString:(NSString *)guid;

- (id<JavaSecurityPublicKey>)publicKeyLookupFromAliasWithNSString:(NSString *)alias;

- (id<JavaSecurityPublicKey>)publicKeyLookupFromGuidWithNSString:(NSString *)guid;

- (OrgJsonJSONObject *)readWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (OrgJsonJSONObject *)readWithNSString:(NSString *)targetGuid
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (OrgJsonJSONObject *)readSecureWithNSString:(NSString *)targetGuid;

- (void)removeAliasWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                 withNSString:(NSString *)name;

- (OrgJsonJSONArray *)selectWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                          withNSString:(NSString *)field
                                                          withNSString:(NSString *)value;

- (OrgJsonJSONArray *)selectWithNSString:(NSString *)field
                            withNSString:(NSString *)value;

- (OrgJsonJSONArray *)selectLookupGroupQueryWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                                          withNSString:(NSString *)guid;

- (OrgJsonJSONArray *)selectLookupGroupQueryWithNSString:(NSString *)guid;

- (OrgJsonJSONArray *)selectNearWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                              withNSString:(NSString *)field
                                                      withOrgJsonJSONArray:(OrgJsonJSONArray *)value
                                                        withJavaLangDouble:(JavaLangDouble *)maxDistance;

- (OrgJsonJSONArray *)selectNearWithNSString:(NSString *)field
                        withOrgJsonJSONArray:(OrgJsonJSONArray *)value
                          withJavaLangDouble:(JavaLangDouble *)maxDistance;

- (OrgJsonJSONArray *)selectQueryWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                               withNSString:(NSString *)query;

- (OrgJsonJSONArray *)selectQueryWithNSString:(NSString *)query;

- (OrgJsonJSONArray *)selectSetupGroupQueryWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                           withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                                         withNSString:(NSString *)publicKey
                                                                         withNSString:(NSString *)query
                                                                              withInt:(jint)interval;

- (OrgJsonJSONArray *)selectSetupGroupQueryWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                                         withNSString:(NSString *)publicKey
                                                                         withNSString:(NSString *)query
                                                                              withInt:(jint)interval;

- (OrgJsonJSONArray *)selectWithinWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                                withNSString:(NSString *)field
                                                        withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (OrgJsonJSONArray *)selectWithinWithNSString:(NSString *)field
                          withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (void)setLocationWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                   withDouble:(jdouble)longitude
                                                   withDouble:(jdouble)latitude;

- (void)setLocationWithNSString:(NSString *)targetGuid
                     withDouble:(jdouble)longitude
                     withDouble:(jdouble)latitude
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)updateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                   withOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (void)updateWithNSString:(NSString *)targetGuid
     withOrgJsonJSONObject:(OrgJsonJSONObject *)json
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsclientClientGNSClientCommands)

FOUNDATION_EXPORT void EduUmassCsGnsclientClientGNSClientCommands_init(EduUmassCsGnsclientClientGNSClientCommands *self);

FOUNDATION_EXPORT EduUmassCsGnsclientClientGNSClientCommands *new_EduUmassCsGnsclientClientGNSClientCommands_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsclientClientGNSClientCommands *create_EduUmassCsGnsclientClientGNSClientCommands_init();

FOUNDATION_EXPORT void EduUmassCsGnsclientClientGNSClientCommands_initWithJavaNetInetSocketAddress_(EduUmassCsGnsclientClientGNSClientCommands *self, JavaNetInetSocketAddress *anyReconfigurator);

FOUNDATION_EXPORT EduUmassCsGnsclientClientGNSClientCommands *new_EduUmassCsGnsclientClientGNSClientCommands_initWithJavaNetInetSocketAddress_(JavaNetInetSocketAddress *anyReconfigurator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsclientClientGNSClientCommands *create_EduUmassCsGnsclientClientGNSClientCommands_initWithJavaNetInetSocketAddress_(JavaNetInetSocketAddress *anyReconfigurator);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsclientClientGNSClientCommands)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsclientClientGNSClientCommands")
