//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./gigapaxos/src/edu/umass/cs/gigapaxos/interfaces/GPShutdownable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGigapaxosInterfacesGPShutdownable")
#ifdef RESTRICT_EduUmassCsGigapaxosInterfacesGPShutdownable
#define INCLUDE_ALL_EduUmassCsGigapaxosInterfacesGPShutdownable 0
#else
#define INCLUDE_ALL_EduUmassCsGigapaxosInterfacesGPShutdownable 1
#endif
#undef RESTRICT_EduUmassCsGigapaxosInterfacesGPShutdownable

#if !defined (EduUmassCsGigapaxosInterfacesGPShutdownable_) && (INCLUDE_ALL_EduUmassCsGigapaxosInterfacesGPShutdownable || defined(INCLUDE_EduUmassCsGigapaxosInterfacesGPShutdownable))
#define EduUmassCsGigapaxosInterfacesGPShutdownable_

@protocol EduUmassCsGigapaxosInterfacesGPShutdownable < JavaObject >

- (void)shutdown;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGigapaxosInterfacesGPShutdownable)

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGigapaxosInterfacesGPShutdownable)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGigapaxosInterfacesGPShutdownable")
