//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsserver/nodeconfig/PortOffsets.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverNodeconfigPortOffsets")
#ifdef RESTRICT_EduUmassCsGnsserverNodeconfigPortOffsets
#define INCLUDE_ALL_EduUmassCsGnsserverNodeconfigPortOffsets 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverNodeconfigPortOffsets 1
#endif
#undef RESTRICT_EduUmassCsGnsserverNodeconfigPortOffsets

#if !defined (EduUmassCsGnsserverNodeconfigPortOffsets_) && (INCLUDE_ALL_EduUmassCsGnsserverNodeconfigPortOffsets || defined(INCLUDE_EduUmassCsGnsserverNodeconfigPortOffsets))
#define EduUmassCsGnsserverNodeconfigPortOffsets_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, EduUmassCsGnsserverNodeconfigPortOffsets_Enum) {
  EduUmassCsGnsserverNodeconfigPortOffsets_Enum_SERVER_ADMIN_PORT = 0,
  EduUmassCsGnsserverNodeconfigPortOffsets_Enum_COLLATING_ADMIN_PORT = 1,
};

@interface EduUmassCsGnsserverNodeconfigPortOffsets : JavaLangEnum < NSCopying > {
 @public
  jint offset_;
}

#pragma mark Public

- (jint)getOffset;

+ (EduUmassCsGnsserverNodeconfigPortOffsets *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(EduUmassCsGnsserverNodeconfigPortOffsets)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EduUmassCsGnsserverNodeconfigPortOffsets *EduUmassCsGnsserverNodeconfigPortOffsets_values_[];

inline EduUmassCsGnsserverNodeconfigPortOffsets *EduUmassCsGnsserverNodeconfigPortOffsets_get_SERVER_ADMIN_PORT();
J2OBJC_ENUM_CONSTANT(EduUmassCsGnsserverNodeconfigPortOffsets, SERVER_ADMIN_PORT)

inline EduUmassCsGnsserverNodeconfigPortOffsets *EduUmassCsGnsserverNodeconfigPortOffsets_get_COLLATING_ADMIN_PORT();
J2OBJC_ENUM_CONSTANT(EduUmassCsGnsserverNodeconfigPortOffsets, COLLATING_ADMIN_PORT)

FOUNDATION_EXPORT IOSObjectArray *EduUmassCsGnsserverNodeconfigPortOffsets_values();

FOUNDATION_EXPORT EduUmassCsGnsserverNodeconfigPortOffsets *EduUmassCsGnsserverNodeconfigPortOffsets_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EduUmassCsGnsserverNodeconfigPortOffsets *EduUmassCsGnsserverNodeconfigPortOffsets_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverNodeconfigPortOffsets)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverNodeconfigPortOffsets")
