//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnscommon/utils/URIEncoderDecoder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnscommonUtilsURIEncoderDecoder")
#ifdef RESTRICT_EduUmassCsGnscommonUtilsURIEncoderDecoder
#define INCLUDE_ALL_EduUmassCsGnscommonUtilsURIEncoderDecoder 0
#else
#define INCLUDE_ALL_EduUmassCsGnscommonUtilsURIEncoderDecoder 1
#endif
#undef RESTRICT_EduUmassCsGnscommonUtilsURIEncoderDecoder

#if !defined (EduUmassCsGnscommonUtilsURIEncoderDecoder_) && (INCLUDE_ALL_EduUmassCsGnscommonUtilsURIEncoderDecoder || defined(INCLUDE_EduUmassCsGnscommonUtilsURIEncoderDecoder))
#define EduUmassCsGnscommonUtilsURIEncoderDecoder_

@interface EduUmassCsGnscommonUtilsURIEncoderDecoder : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)decodeWithNSString:(NSString *)s;

+ (NSString *)quoteIllegalWithNSString:(NSString *)s;

#pragma mark Package-Private

+ (NSString *)encodeOthersWithNSString:(NSString *)s;

+ (void)validateWithNSString:(NSString *)s
                withNSString:(NSString *)legal;

+ (void)validateSimpleWithNSString:(NSString *)s
                      withNSString:(NSString *)legal;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnscommonUtilsURIEncoderDecoder)

FOUNDATION_EXPORT void EduUmassCsGnscommonUtilsURIEncoderDecoder_init(EduUmassCsGnscommonUtilsURIEncoderDecoder *self);

FOUNDATION_EXPORT EduUmassCsGnscommonUtilsURIEncoderDecoder *new_EduUmassCsGnscommonUtilsURIEncoderDecoder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnscommonUtilsURIEncoderDecoder *create_EduUmassCsGnscommonUtilsURIEncoderDecoder_init();

FOUNDATION_EXPORT void EduUmassCsGnscommonUtilsURIEncoderDecoder_validateWithNSString_withNSString_(NSString *s, NSString *legal);

FOUNDATION_EXPORT void EduUmassCsGnscommonUtilsURIEncoderDecoder_validateSimpleWithNSString_withNSString_(NSString *s, NSString *legal);

FOUNDATION_EXPORT NSString *EduUmassCsGnscommonUtilsURIEncoderDecoder_quoteIllegalWithNSString_(NSString *s);

FOUNDATION_EXPORT NSString *EduUmassCsGnscommonUtilsURIEncoderDecoder_encodeOthersWithNSString_(NSString *s);

FOUNDATION_EXPORT NSString *EduUmassCsGnscommonUtilsURIEncoderDecoder_decodeWithNSString_(NSString *s);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnscommonUtilsURIEncoderDecoder)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnscommonUtilsURIEncoderDecoder")
