//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsserver/utils/JSONUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverUtilsJSONUtils")
#ifdef RESTRICT_EduUmassCsGnsserverUtilsJSONUtils
#define INCLUDE_ALL_EduUmassCsGnsserverUtilsJSONUtils 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverUtilsJSONUtils 1
#endif
#undef RESTRICT_EduUmassCsGnsserverUtilsJSONUtils

#if !defined (EduUmassCsGnsserverUtilsJSONUtils_) && (INCLUDE_ALL_EduUmassCsGnsserverUtilsJSONUtils || defined(INCLUDE_EduUmassCsGnsserverUtilsJSONUtils))
#define EduUmassCsGnsserverUtilsJSONUtils_

@class EduUmassCsGnsserverUtilsResultValue;
@class JavaUtilArrayList;
@class JavaUtilHashSet;
@class OrgJsonJSONArray;
@class OrgJsonJSONObject;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface EduUmassCsGnsserverUtilsJSONUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (OrgJsonJSONObject *)copyJsonObjectWithOrgJsonJSONObject:(OrgJsonJSONObject *)record OBJC_METHOD_FAMILY_NONE;

+ (jboolean)JSONArrayContainsWithId:(id)object
               withOrgJsonJSONArray:(OrgJsonJSONArray *)jsonArray;

+ (JavaUtilArrayList *)JSONArrayToArrayListWithOrgJsonJSONArray:(OrgJsonJSONArray *)jsonArray;

+ (JavaUtilArrayList *)JSONArrayToArrayListIntegerWithOrgJsonJSONArray:(OrgJsonJSONArray *)jsonArray;

+ (JavaUtilArrayList *)JSONArrayToArrayListStringWithOrgJsonJSONArray:(OrgJsonJSONArray *)jsonArray;

+ (JavaUtilHashSet *)JSONArrayToHashSetWithOrgJsonJSONArray:(OrgJsonJSONArray *)jsonArray;

+ (EduUmassCsGnsserverUtilsResultValue *)JSONArrayToResultValueWithOrgJsonJSONArray:(OrgJsonJSONArray *)jsonArray;

+ (id<JavaUtilSet>)JSONArrayToSetIntegerWithOrgJsonJSONArray:(OrgJsonJSONArray *)json;

+ (id<JavaUtilSet>)JSONArrayToSetStringWithOrgJsonJSONArray:(OrgJsonJSONArray *)json;

+ (id<JavaUtilMap>)JSONObjectToMapWithOrgJsonJSONObject:(OrgJsonJSONObject *)json;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsserverUtilsJSONUtils)

FOUNDATION_EXPORT void EduUmassCsGnsserverUtilsJSONUtils_init(EduUmassCsGnsserverUtilsJSONUtils *self);

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsJSONUtils *new_EduUmassCsGnsserverUtilsJSONUtils_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsJSONUtils *create_EduUmassCsGnsserverUtilsJSONUtils_init();

FOUNDATION_EXPORT OrgJsonJSONObject *EduUmassCsGnsserverUtilsJSONUtils_copyJsonObjectWithOrgJsonJSONObject_(OrgJsonJSONObject *record);

FOUNDATION_EXPORT JavaUtilArrayList *EduUmassCsGnsserverUtilsJSONUtils_JSONArrayToArrayListWithOrgJsonJSONArray_(OrgJsonJSONArray *jsonArray);

FOUNDATION_EXPORT JavaUtilArrayList *EduUmassCsGnsserverUtilsJSONUtils_JSONArrayToArrayListStringWithOrgJsonJSONArray_(OrgJsonJSONArray *jsonArray);

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsResultValue *EduUmassCsGnsserverUtilsJSONUtils_JSONArrayToResultValueWithOrgJsonJSONArray_(OrgJsonJSONArray *jsonArray);

FOUNDATION_EXPORT JavaUtilHashSet *EduUmassCsGnsserverUtilsJSONUtils_JSONArrayToHashSetWithOrgJsonJSONArray_(OrgJsonJSONArray *jsonArray);

FOUNDATION_EXPORT JavaUtilArrayList *EduUmassCsGnsserverUtilsJSONUtils_JSONArrayToArrayListIntegerWithOrgJsonJSONArray_(OrgJsonJSONArray *jsonArray);

FOUNDATION_EXPORT id<JavaUtilSet> EduUmassCsGnsserverUtilsJSONUtils_JSONArrayToSetIntegerWithOrgJsonJSONArray_(OrgJsonJSONArray *json);

FOUNDATION_EXPORT id<JavaUtilSet> EduUmassCsGnsserverUtilsJSONUtils_JSONArrayToSetStringWithOrgJsonJSONArray_(OrgJsonJSONArray *json);

FOUNDATION_EXPORT id<JavaUtilMap> EduUmassCsGnsserverUtilsJSONUtils_JSONObjectToMapWithOrgJsonJSONObject_(OrgJsonJSONObject *json);

FOUNDATION_EXPORT jboolean EduUmassCsGnsserverUtilsJSONUtils_JSONArrayContainsWithId_withOrgJsonJSONArray_(id object, OrgJsonJSONArray *jsonArray);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverUtilsJSONUtils)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverUtilsJSONUtils")
