//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsserver/utils/ResultValue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverUtilsResultValue")
#ifdef RESTRICT_EduUmassCsGnsserverUtilsResultValue
#define INCLUDE_ALL_EduUmassCsGnsserverUtilsResultValue 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverUtilsResultValue 1
#endif
#undef RESTRICT_EduUmassCsGnsserverUtilsResultValue

#if !defined (EduUmassCsGnsserverUtilsResultValue_) && (INCLUDE_ALL_EduUmassCsGnsserverUtilsResultValue || defined(INCLUDE_EduUmassCsGnsserverUtilsResultValue))
#define EduUmassCsGnsserverUtilsResultValue_

#define RESTRICT_JavaUtilArrayList 1
#define INCLUDE_JavaUtilArrayList 1
#include "java/util/ArrayList.h"

@class EduUmassCsGnsserverUtilsResultValueString;
@protocol JavaUtilCollection;
@protocol JavaUtilSet;

@interface EduUmassCsGnsserverUtilsResultValue : JavaUtilArrayList

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (instancetype)initWithNSString:(NSString *)string;

- (EduUmassCsGnsserverUtilsResultValueString *)toResultValueString;

- (id<JavaUtilSet>)toStringSet;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsserverUtilsResultValue)

FOUNDATION_EXPORT void EduUmassCsGnsserverUtilsResultValue_init(EduUmassCsGnsserverUtilsResultValue *self);

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsResultValue *new_EduUmassCsGnsserverUtilsResultValue_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsResultValue *create_EduUmassCsGnsserverUtilsResultValue_init();

FOUNDATION_EXPORT void EduUmassCsGnsserverUtilsResultValue_initWithJavaUtilCollection_(EduUmassCsGnsserverUtilsResultValue *self, id<JavaUtilCollection> collection);

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsResultValue *new_EduUmassCsGnsserverUtilsResultValue_initWithJavaUtilCollection_(id<JavaUtilCollection> collection) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsResultValue *create_EduUmassCsGnsserverUtilsResultValue_initWithJavaUtilCollection_(id<JavaUtilCollection> collection);

FOUNDATION_EXPORT void EduUmassCsGnsserverUtilsResultValue_initWithNSString_(EduUmassCsGnsserverUtilsResultValue *self, NSString *string);

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsResultValue *new_EduUmassCsGnsserverUtilsResultValue_initWithNSString_(NSString *string) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverUtilsResultValue *create_EduUmassCsGnsserverUtilsResultValue_initWithNSString_(NSString *string);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverUtilsResultValue)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverUtilsResultValue")
