//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsserver/utils/Shutdownable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverUtilsShutdownable")
#ifdef RESTRICT_EduUmassCsGnsserverUtilsShutdownable
#define INCLUDE_ALL_EduUmassCsGnsserverUtilsShutdownable 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverUtilsShutdownable 1
#endif
#undef RESTRICT_EduUmassCsGnsserverUtilsShutdownable

#if !defined (EduUmassCsGnsserverUtilsShutdownable_) && (INCLUDE_ALL_EduUmassCsGnsserverUtilsShutdownable || defined(INCLUDE_EduUmassCsGnsserverUtilsShutdownable))
#define EduUmassCsGnsserverUtilsShutdownable_

@protocol EduUmassCsGnsserverUtilsShutdownable < JavaObject >

- (void)shutdown;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsserverUtilsShutdownable)

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverUtilsShutdownable)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverUtilsShutdownable")
