//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsclient/client/http/HttpClient.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsclientClientHttpHttpClient")
#ifdef RESTRICT_EduUmassCsGnsclientClientHttpHttpClient
#define INCLUDE_ALL_EduUmassCsGnsclientClientHttpHttpClient 0
#else
#define INCLUDE_ALL_EduUmassCsGnsclientClientHttpHttpClient 1
#endif
#undef RESTRICT_EduUmassCsGnsclientClientHttpHttpClient

#if !defined (EduUmassCsGnsclientClientHttpHttpClient_) && (INCLUDE_ALL_EduUmassCsGnsclientClientHttpHttpClient || defined(INCLUDE_EduUmassCsGnsclientClientHttpHttpClient))
#define EduUmassCsGnsclientClientHttpHttpClient_

@class EduUmassCsGnsclientClientUtilGuidEntry;
@class EduUmassCsGnscommonAclAccessType;
@class JavaLangDouble;
@class JavaUtilArrayList;
@class OrgJsonJSONArray;
@class OrgJsonJSONObject;
@protocol JavaSecurityPublicKey;

@interface EduUmassCsGnsclientClientHttpHttpClient : NSObject

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)host
                         withInt:(jint)port;

- (EduUmassCsGnsclientClientUtilGuidEntry *)accountGuidCreateWithNSString:(NSString *)alias
                                                             withNSString:(NSString *)password;

- (void)accountGuidRemoveWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (NSString *)accountGuidVerifyWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                             withNSString:(NSString *)code;

- (void)aclAddWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
        withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                      withNSString:(NSString *)field
                                      withNSString:(NSString *)accesserGuid;

- (OrgJsonJSONArray *)aclGetWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
                      withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                    withNSString:(NSString *)field
                                                    withNSString:(NSString *)accesserGuid;

- (void)aclRemoveWithEduUmassCsGnscommonAclAccessType:(EduUmassCsGnscommonAclAccessType *)accessType
           withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                         withNSString:(NSString *)field
                                         withNSString:(NSString *)accesserGuid;

- (void)addAliasWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                              withNSString:(NSString *)name;

- (void)checkConnectivity;

- (void)close;

- (void)fieldAppendWithNSString:(NSString *)targetGuid
                   withNSString:(NSString *)field
                   withNSString:(NSString *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendListWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
               withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendOrCreateWithNSString:(NSString *)targetGuid
                           withNSString:(NSString *)field
                           withNSString:(NSString *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendOrCreateListWithNSString:(NSString *)targetGuid
                               withNSString:(NSString *)field
                       withOrgJsonJSONArray:(OrgJsonJSONArray *)value
 withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendWithSetSemanticsWithNSString:(NSString *)targetGuid
                                   withNSString:(NSString *)field
                           withOrgJsonJSONArray:(OrgJsonJSONArray *)value
     withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldAppendWithSetSemanticsWithNSString:(NSString *)targetGuid
                                   withNSString:(NSString *)field
                                   withNSString:(NSString *)value
     withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldClearWithNSString:(NSString *)targetGuid
                  withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldClearWithNSString:(NSString *)targetGuid
                  withNSString:(NSString *)field
          withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldCreateIndexWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                      withNSString:(NSString *)field
                                                      withNSString:(NSString *)index;

- (void)fieldCreateListWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
               withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldCreateSingleElementListWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                                  withNSString:(NSString *)field
                                                                  withNSString:(NSString *)value;

- (void)fieldCreateSingleElementListWithNSString:(NSString *)targetGuid
                                    withNSString:(NSString *)field
                                    withNSString:(NSString *)value
      withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (jboolean)fieldExistsWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                     withNSString:(NSString *)field;

- (jboolean)fieldExistsWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (NSString *)fieldReadWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                            withJavaUtilArrayList:(JavaUtilArrayList *)fields;

- (NSString *)fieldReadWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                     withNSString:(NSString *)field;

- (NSString *)fieldReadWithNSString:(NSString *)targetGuid
              withJavaUtilArrayList:(JavaUtilArrayList *)fields
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (NSString *)fieldReadWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (OrgJsonJSONArray *)fieldReadArrayWithNSString:(NSString *)guid
                                    withNSString:(NSString *)field
      withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (NSString *)fieldReadFirstElementWithNSString:(NSString *)guid
                                   withNSString:(NSString *)field
     withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (void)fieldRemoveWithNSString:(NSString *)targetGuid
                   withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceFirstElementWithNSString:(NSString *)targetGuid
                                withNSString:(NSString *)field
                                withNSString:(NSString *)value
  withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceListWithNSString:(NSString *)targetGuid
                        withNSString:(NSString *)field
                withOrgJsonJSONArray:(OrgJsonJSONArray *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceOrCreateWithNSString:(NSString *)targetGuid
                            withNSString:(NSString *)field
                            withNSString:(NSString *)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldReplaceOrCreateListWithNSString:(NSString *)targetGuid
                                withNSString:(NSString *)field
                        withOrgJsonJSONArray:(OrgJsonJSONArray *)value
  withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSetElementWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
                       withNSString:(NSString *)newValue
                            withInt:(jint)index
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSetNullWithNSString:(NSString *)targetGuid
                    withNSString:(NSString *)field
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSubstituteWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
               withOrgJsonJSONArray:(OrgJsonJSONArray *)newValue
               withOrgJsonJSONArray:(OrgJsonJSONArray *)oldValue
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldSubstituteWithNSString:(NSString *)targetGuid
                       withNSString:(NSString *)field
                       withNSString:(NSString *)newValue
                       withNSString:(NSString *)oldValue
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)fieldUpdateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)targetGuid
                                                 withNSString:(NSString *)field
                                                       withId:(id)value;

- (void)fieldUpdateWithNSString:(NSString *)targetGuid
                   withNSString:(NSString *)field
                         withId:(id)value
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (OrgJsonJSONArray *)getAliasesWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (NSString *)getGNSProvider;

- (NSString *)getHelp;

- (OrgJsonJSONArray *)getLocationWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)readerGuid
                                                               withNSString:(NSString *)targetGuid;

- (jint)getReadRetries;

- (jint)getReadTimeout;

- (void)groupAddGuidWithNSString:(NSString *)groupGuid
                    withNSString:(NSString *)guidToAdd
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupAddGuidsWithNSString:(NSString *)groupGuid
             withOrgJsonJSONArray:(OrgJsonJSONArray *)members
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupAddMembershipReadPermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                      withNSString:(NSString *)guidToAuthorize;

- (void)groupAddMembershipUpdatePermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                        withNSString:(NSString *)guidToAuthorize;

- (OrgJsonJSONArray *)groupGetMembersWithNSString:(NSString *)groupGuid
       withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (void)groupRemoveGuidWithNSString:(NSString *)guid
                       withNSString:(NSString *)guidToRemove
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupRemoveGuidsWithNSString:(NSString *)guid
                withOrgJsonJSONArray:(OrgJsonJSONArray *)members
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

- (void)groupRemoveMembershipReadPermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                         withNSString:(NSString *)guidToUnauthorize;

- (void)groupRemoveMembershipUpdatePermissionWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)groupGuid
                                                                           withNSString:(NSString *)guidToUnauthorize;

- (EduUmassCsGnsclientClientUtilGuidEntry *)guidCreateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                                                    withNSString:(NSString *)alias;

- (OrgJsonJSONArray *)guidGetGroupsWithNSString:(NSString *)groupGuid
     withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (void)guidRemoveWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (void)guidRemoveWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)accountGuid
                                                withNSString:(NSString *)guidToRemove;

- (OrgJsonJSONObject *)lookupAccountRecordWithNSString:(NSString *)gaccountGuid;

- (NSString *)lookupGuidWithNSString:(NSString *)alias;

- (OrgJsonJSONObject *)lookupGuidRecordWithNSString:(NSString *)guid;

- (NSString *)lookupPrimaryGuidWithNSString:(NSString *)guid;

- (id<JavaSecurityPublicKey>)publicKeyLookupFromAliasWithNSString:(NSString *)alias;

- (id<JavaSecurityPublicKey>)publicKeyLookupFromGuidWithNSString:(NSString *)guid;

- (OrgJsonJSONObject *)readWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (OrgJsonJSONObject *)readWithNSString:(NSString *)targetGuid
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader;

- (void)removeAliasWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                                 withNSString:(NSString *)name;

- (OrgJsonJSONArray *)selectWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                          withNSString:(NSString *)field
                                                          withNSString:(NSString *)value;

- (OrgJsonJSONArray *)selectWithNSString:(NSString *)field
                            withNSString:(NSString *)value;

- (OrgJsonJSONArray *)selectLookupGroupQueryWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                                          withNSString:(NSString *)groupGuid;

- (OrgJsonJSONArray *)selectLookupGroupQueryWithNSString:(NSString *)guid;

- (OrgJsonJSONArray *)selectNearWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                              withNSString:(NSString *)field
                                                      withOrgJsonJSONArray:(OrgJsonJSONArray *)value
                                                        withJavaLangDouble:(JavaLangDouble *)maxDistance;

- (OrgJsonJSONArray *)selectNearWithNSString:(NSString *)field
                        withOrgJsonJSONArray:(OrgJsonJSONArray *)value
                          withJavaLangDouble:(JavaLangDouble *)maxDistance;

- (OrgJsonJSONArray *)selectQueryWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                               withNSString:(NSString *)query;

- (OrgJsonJSONArray *)selectQueryWithNSString:(NSString *)query;

- (OrgJsonJSONArray *)selectSetupGroupQueryWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                                         withNSString:(NSString *)groupGuid
                                                                         withNSString:(NSString *)query;

- (OrgJsonJSONArray *)selectSetupGroupQueryWithNSString:(NSString *)guid
                                           withNSString:(NSString *)query;

- (OrgJsonJSONArray *)selectWithinWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)reader
                                                                withNSString:(NSString *)field
                                                        withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (OrgJsonJSONArray *)selectWithinWithNSString:(NSString *)field
                          withOrgJsonJSONArray:(OrgJsonJSONArray *)value;

- (void)setLocationWithDouble:(jdouble)longitude
                   withDouble:(jdouble)latitude
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid;

- (void)setReadRetriesWithInt:(jint)readRetries;

- (void)setReadTimeoutWithInt:(jint)readTimeout;

- (void)updateWithEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)guid
                                   withOrgJsonJSONObject:(OrgJsonJSONObject *)json;

- (void)updateWithNSString:(NSString *)targetGuid
     withOrgJsonJSONObject:(OrgJsonJSONObject *)json
withEduUmassCsGnsclientClientUtilGuidEntry:(EduUmassCsGnsclientClientUtilGuidEntry *)writer;

@end

J2OBJC_STATIC_INIT(EduUmassCsGnsclientClientHttpHttpClient)

inline jboolean EduUmassCsGnsclientClientHttpHttpClient_get_IS_ANDROID();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jboolean EduUmassCsGnsclientClientHttpHttpClient_IS_ANDROID;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(EduUmassCsGnsclientClientHttpHttpClient, IS_ANDROID, jboolean)

FOUNDATION_EXPORT void EduUmassCsGnsclientClientHttpHttpClient_initWithNSString_withInt_(EduUmassCsGnsclientClientHttpHttpClient *self, NSString *host, jint port);

FOUNDATION_EXPORT EduUmassCsGnsclientClientHttpHttpClient *new_EduUmassCsGnsclientClientHttpHttpClient_initWithNSString_withInt_(NSString *host, jint port) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsclientClientHttpHttpClient *create_EduUmassCsGnsclientClientHttpHttpClient_initWithNSString_withInt_(NSString *host, jint port);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsclientClientHttpHttpClient)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsclientClientHttpHttpClient")
