//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./gigapaxos/src/edu/umass/cs/utils/ClassFinder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsUtilsClassFinder")
#ifdef RESTRICT_EduUmassCsUtilsClassFinder
#define INCLUDE_ALL_EduUmassCsUtilsClassFinder 0
#else
#define INCLUDE_ALL_EduUmassCsUtilsClassFinder 1
#endif
#undef RESTRICT_EduUmassCsUtilsClassFinder

#if !defined (EduUmassCsUtilsClassFinder_) && (INCLUDE_ALL_EduUmassCsUtilsClassFinder || defined(INCLUDE_EduUmassCsUtilsClassFinder))
#define EduUmassCsUtilsClassFinder_

@class IOSClass;
@class IOSObjectArray;
@protocol JavaUtilList;

@interface EduUmassCsUtilsClassFinder : NSObject

#pragma mark Public

- (instancetype)init;

+ (id<JavaUtilList>)findWithNSString:(NSString *)scannedPackage;

+ (id<JavaUtilList>)findRegexWithNSString:(NSString *)regex;

+ (id<JavaUtilList>)findRestWithIOSClass:(IOSClass *)clazz;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsUtilsClassFinder)

FOUNDATION_EXPORT void EduUmassCsUtilsClassFinder_init(EduUmassCsUtilsClassFinder *self);

FOUNDATION_EXPORT EduUmassCsUtilsClassFinder *new_EduUmassCsUtilsClassFinder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsUtilsClassFinder *create_EduUmassCsUtilsClassFinder_init();

FOUNDATION_EXPORT id<JavaUtilList> EduUmassCsUtilsClassFinder_findWithNSString_(NSString *scannedPackage);

FOUNDATION_EXPORT id<JavaUtilList> EduUmassCsUtilsClassFinder_findRegexWithNSString_(NSString *regex);

FOUNDATION_EXPORT id<JavaUtilList> EduUmassCsUtilsClassFinder_findRestWithIOSClass_(IOSClass *clazz);

FOUNDATION_EXPORT void EduUmassCsUtilsClassFinder_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsUtilsClassFinder)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsUtilsClassFinder")
