//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./gigapaxos/src/edu/umass/cs/utils/Repeat.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsUtilsRepeat")
#ifdef RESTRICT_EduUmassCsUtilsRepeat
#define INCLUDE_ALL_EduUmassCsUtilsRepeat 0
#else
#define INCLUDE_ALL_EduUmassCsUtilsRepeat 1
#endif
#undef RESTRICT_EduUmassCsUtilsRepeat

#if !defined (EduUmassCsUtilsRepeat_) && (INCLUDE_ALL_EduUmassCsUtilsRepeat || defined(INCLUDE_EduUmassCsUtilsRepeat))
#define EduUmassCsUtilsRepeat_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol EduUmassCsUtilsRepeat < JavaLangAnnotationAnnotation >

@property (readonly) jint times;

@end

@interface EduUmassCsUtilsRepeat : NSObject < EduUmassCsUtilsRepeat > {
 @public
  jint times_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsUtilsRepeat)

FOUNDATION_EXPORT id<EduUmassCsUtilsRepeat> create_EduUmassCsUtilsRepeat(jint times);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsUtilsRepeat)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsUtilsRepeat")
