//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./gigapaxos/src/edu/umass/cs/utils/RepeatRule.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsUtilsRepeatRule")
#ifdef RESTRICT_EduUmassCsUtilsRepeatRule
#define INCLUDE_ALL_EduUmassCsUtilsRepeatRule 0
#else
#define INCLUDE_ALL_EduUmassCsUtilsRepeatRule 1
#endif
#undef RESTRICT_EduUmassCsUtilsRepeatRule

#if !defined (EduUmassCsUtilsRepeatRule_) && (INCLUDE_ALL_EduUmassCsUtilsRepeatRule || defined(INCLUDE_EduUmassCsUtilsRepeatRule))
#define EduUmassCsUtilsRepeatRule_

#define RESTRICT_OrgJunitRulesTestRule 1
#define INCLUDE_OrgJunitRulesTestRule 1
#include "org/junit/rules/TestRule.h"

@class EduUmassCsUtilsRepeatRule_RepeatStatement;
@class OrgJunitRunnerDescription;
@class OrgJunitRunnersModelStatement;

@interface EduUmassCsUtilsRepeatRule : NSObject < OrgJunitRulesTestRule > {
 @public
  EduUmassCsUtilsRepeatRule_RepeatStatement *result_;
}

#pragma mark Public

- (instancetype)init;

- (OrgJunitRunnersModelStatement *)applyWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)statement
                                            withOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (jint)times;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsUtilsRepeatRule)

J2OBJC_FIELD_SETTER(EduUmassCsUtilsRepeatRule, result_, EduUmassCsUtilsRepeatRule_RepeatStatement *)

FOUNDATION_EXPORT void EduUmassCsUtilsRepeatRule_init(EduUmassCsUtilsRepeatRule *self);

FOUNDATION_EXPORT EduUmassCsUtilsRepeatRule *new_EduUmassCsUtilsRepeatRule_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsUtilsRepeatRule *create_EduUmassCsUtilsRepeatRule_init();

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsUtilsRepeatRule)

#endif

#if !defined (EduUmassCsUtilsRepeatRule_RepeatStatement_) && (INCLUDE_ALL_EduUmassCsUtilsRepeatRule || defined(INCLUDE_EduUmassCsUtilsRepeatRule_RepeatStatement))
#define EduUmassCsUtilsRepeatRule_RepeatStatement_

#define RESTRICT_OrgJunitRunnersModelStatement 1
#define INCLUDE_OrgJunitRunnersModelStatement 1
#include "org/junit/runners/model/Statement.h"

@interface EduUmassCsUtilsRepeatRule_RepeatStatement : OrgJunitRunnersModelStatement

#pragma mark Public

- (void)evaluate;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsUtilsRepeatRule_RepeatStatement)

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsUtilsRepeatRule_RepeatStatement)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsUtilsRepeatRule")
