//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsserver/gnsapp/GNSAppUtil.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSAppUtil")
#ifdef RESTRICT_EduUmassCsGnsserverGnsappGNSAppUtil
#define INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSAppUtil 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSAppUtil 1
#endif
#undef RESTRICT_EduUmassCsGnsserverGnsappGNSAppUtil

#if !defined (EduUmassCsGnsserverGnsappGNSAppUtil_) && (INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSAppUtil || defined(INCLUDE_EduUmassCsGnsserverGnsappGNSAppUtil))
#define EduUmassCsGnsserverGnsappGNSAppUtil_

@class EduUmassCsNioNioutilsNIOHeader;
@class IOSByteArray;
@protocol EduUmassCsGigapaxosInterfacesRequest;
@protocol EduUmassCsNioInterfacesStringifiable;

@interface EduUmassCsGnsserverGnsappGNSAppUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (id<EduUmassCsGigapaxosInterfacesRequest>)getRequestStaticWithByteArray:(IOSByteArray *)msgBytes
                                       withEduUmassCsNioNioutilsNIOHeader:(EduUmassCsNioNioutilsNIOHeader *)header
                                 withEduUmassCsNioInterfacesStringifiable:(id<EduUmassCsNioInterfacesStringifiable>)unstringer;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsserverGnsappGNSAppUtil)

FOUNDATION_EXPORT void EduUmassCsGnsserverGnsappGNSAppUtil_init(EduUmassCsGnsserverGnsappGNSAppUtil *self);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappGNSAppUtil *new_EduUmassCsGnsserverGnsappGNSAppUtil_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappGNSAppUtil *create_EduUmassCsGnsserverGnsappGNSAppUtil_init();

FOUNDATION_EXPORT id<EduUmassCsGigapaxosInterfacesRequest> EduUmassCsGnsserverGnsappGNSAppUtil_getRequestStaticWithByteArray_withEduUmassCsNioNioutilsNIOHeader_withEduUmassCsNioInterfacesStringifiable_(IOSByteArray *msgBytes, EduUmassCsNioNioutilsNIOHeader *header, id<EduUmassCsNioInterfacesStringifiable> unstringer);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverGnsappGNSAppUtil)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSAppUtil")
