//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsserver/gnsapp/GNSCommandInternal.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSCommandInternal")
#ifdef RESTRICT_EduUmassCsGnsserverGnsappGNSCommandInternal
#define INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSCommandInternal 0
#else
#define INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSCommandInternal 1
#endif
#undef RESTRICT_EduUmassCsGnsserverGnsappGNSCommandInternal

#if !defined (EduUmassCsGnsserverGnsappGNSCommandInternal_) && (INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSCommandInternal || defined(INCLUDE_EduUmassCsGnsserverGnsappGNSCommandInternal))
#define EduUmassCsGnsserverGnsappGNSCommandInternal_

#define RESTRICT_EduUmassCsGnsserverGnsappPacketInternalCommandPacket 1
#define INCLUDE_EduUmassCsGnsserverGnsappPacketInternalCommandPacket 1
#include "edu/umass/cs/gnsserver/gnsapp/packet/InternalCommandPacket.h"

@class EduUmassCsGnscommonCommandType;
@class EduUmassCsGnsserverUtilsResultValue;
@class IOSObjectArray;
@class JavaUtilArrayList;
@class OrgJsonJSONObject;
@protocol EduUmassCsGnsserverInterfacesInternalRequestHeader;

@interface EduUmassCsGnsserverGnsappGNSCommandInternal : EduUmassCsGnsserverGnsappPacketInternalCommandPacket

#pragma mark Public

+ (EduUmassCsGnsserverGnsappPacketInternalCommandPacket *)fieldReadWithNSString:(NSString *)targetGUID
                                                          withJavaUtilArrayList:(JavaUtilArrayList *)fields
                         withEduUmassCsGnsserverInterfacesInternalRequestHeader:(id<EduUmassCsGnsserverInterfacesInternalRequestHeader>)header;

+ (EduUmassCsGnsserverGnsappPacketInternalCommandPacket *)fieldReadWithNSString:(NSString *)targetGUID
                                                                   withNSString:(NSString *)field
                         withEduUmassCsGnsserverInterfacesInternalRequestHeader:(id<EduUmassCsGnsserverInterfacesInternalRequestHeader>)header;

+ (EduUmassCsGnsserverGnsappPacketInternalCommandPacket *)fieldRemoveWithNSString:(NSString *)guid
                                                                     withNSString:(NSString *)field
                                                                     withNSString:(NSString *)value
                           withEduUmassCsGnsserverInterfacesInternalRequestHeader:(id<EduUmassCsGnsserverInterfacesInternalRequestHeader>)header;

+ (EduUmassCsGnsserverGnsappPacketInternalCommandPacket *)fieldRemoveListWithNSString:(NSString *)guid
                                                                         withNSString:(NSString *)field
                                              withEduUmassCsGnsserverUtilsResultValue:(EduUmassCsGnsserverUtilsResultValue *)value
                               withEduUmassCsGnsserverInterfacesInternalRequestHeader:(id<EduUmassCsGnsserverInterfacesInternalRequestHeader>)header;

+ (EduUmassCsGnsserverGnsappPacketInternalCommandPacket *)fieldUpdateWithEduUmassCsGnsserverInterfacesInternalRequestHeader:(id<EduUmassCsGnsserverInterfacesInternalRequestHeader>)header
                                                                                         withEduUmassCsGnscommonCommandType:(EduUmassCsGnscommonCommandType *)type
                                                                                                          withNSObjectArray:(IOSObjectArray *)keysAndValues;

+ (EduUmassCsGnsserverGnsappPacketInternalCommandPacket *)fieldUpdateWithNSString:(NSString *)targetGUID
                                                                     withNSString:(NSString *)field
                                                                           withId:(id)value
                           withEduUmassCsGnsserverInterfacesInternalRequestHeader:(id<EduUmassCsGnsserverInterfacesInternalRequestHeader>)header;

#pragma mark Protected

- (instancetype)initWithEduUmassCsGnsserverInterfacesInternalRequestHeader:(id<EduUmassCsGnsserverInterfacesInternalRequestHeader>)header
                                                     withOrgJsonJSONObject:(OrgJsonJSONObject *)command;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsserverGnsappGNSCommandInternal)

FOUNDATION_EXPORT void EduUmassCsGnsserverGnsappGNSCommandInternal_initWithEduUmassCsGnsserverInterfacesInternalRequestHeader_withOrgJsonJSONObject_(EduUmassCsGnsserverGnsappGNSCommandInternal *self, id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header, OrgJsonJSONObject *command);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappGNSCommandInternal *new_EduUmassCsGnsserverGnsappGNSCommandInternal_initWithEduUmassCsGnsserverInterfacesInternalRequestHeader_withOrgJsonJSONObject_(id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header, OrgJsonJSONObject *command) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappGNSCommandInternal *create_EduUmassCsGnsserverGnsappGNSCommandInternal_initWithEduUmassCsGnsserverInterfacesInternalRequestHeader_withOrgJsonJSONObject_(id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header, OrgJsonJSONObject *command);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappPacketInternalCommandPacket *EduUmassCsGnsserverGnsappGNSCommandInternal_fieldReadWithNSString_withNSString_withEduUmassCsGnsserverInterfacesInternalRequestHeader_(NSString *targetGUID, NSString *field, id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappPacketInternalCommandPacket *EduUmassCsGnsserverGnsappGNSCommandInternal_fieldReadWithNSString_withJavaUtilArrayList_withEduUmassCsGnsserverInterfacesInternalRequestHeader_(NSString *targetGUID, JavaUtilArrayList *fields, id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappPacketInternalCommandPacket *EduUmassCsGnsserverGnsappGNSCommandInternal_fieldUpdateWithNSString_withNSString_withId_withEduUmassCsGnsserverInterfacesInternalRequestHeader_(NSString *targetGUID, NSString *field, id value, id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappPacketInternalCommandPacket *EduUmassCsGnsserverGnsappGNSCommandInternal_fieldUpdateWithEduUmassCsGnsserverInterfacesInternalRequestHeader_withEduUmassCsGnscommonCommandType_withNSObjectArray_(id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header, EduUmassCsGnscommonCommandType *type, IOSObjectArray *keysAndValues);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappPacketInternalCommandPacket *EduUmassCsGnsserverGnsappGNSCommandInternal_fieldRemoveWithNSString_withNSString_withNSString_withEduUmassCsGnsserverInterfacesInternalRequestHeader_(NSString *guid, NSString *field, NSString *value, id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header);

FOUNDATION_EXPORT EduUmassCsGnsserverGnsappPacketInternalCommandPacket *EduUmassCsGnsserverGnsappGNSCommandInternal_fieldRemoveListWithNSString_withNSString_withEduUmassCsGnsserverUtilsResultValue_withEduUmassCsGnsserverInterfacesInternalRequestHeader_(NSString *guid, NSString *field, EduUmassCsGnsserverUtilsResultValue *value, id<EduUmassCsGnsserverInterfacesInternalRequestHeader> header);

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsserverGnsappGNSCommandInternal)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsserverGnsappGNSCommandInternal")
