//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./GNS/src/edu/umass/cs/gnsclient/client/http/android/DownloadTask.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EduUmassCsGnsclientClientHttpAndroidDownloadTask")
#ifdef RESTRICT_EduUmassCsGnsclientClientHttpAndroidDownloadTask
#define INCLUDE_ALL_EduUmassCsGnsclientClientHttpAndroidDownloadTask 0
#else
#define INCLUDE_ALL_EduUmassCsGnsclientClientHttpAndroidDownloadTask 1
#endif
#undef RESTRICT_EduUmassCsGnsclientClientHttpAndroidDownloadTask

#if !defined (EduUmassCsGnsclientClientHttpAndroidDownloadTask_) && (INCLUDE_ALL_EduUmassCsGnsclientClientHttpAndroidDownloadTask || defined(INCLUDE_EduUmassCsGnsclientClientHttpAndroidDownloadTask))
#define EduUmassCsGnsclientClientHttpAndroidDownloadTask_

#define RESTRICT_AndroidOsAsyncTask 1
#define INCLUDE_AndroidOsAsyncTask 1
#include "android/os/AsyncTask.h"

@class IOSObjectArray;

@interface EduUmassCsGnsclientClientHttpAndroidDownloadTask : AndroidOsAsyncTask

#pragma mark Public

- (instancetype)init;

#pragma mark Protected

- (id)doInBackgroundWithNSObjectArray:(IOSObjectArray *)urls;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUmassCsGnsclientClientHttpAndroidDownloadTask)

FOUNDATION_EXPORT void EduUmassCsGnsclientClientHttpAndroidDownloadTask_init(EduUmassCsGnsclientClientHttpAndroidDownloadTask *self);

FOUNDATION_EXPORT EduUmassCsGnsclientClientHttpAndroidDownloadTask *new_EduUmassCsGnsclientClientHttpAndroidDownloadTask_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EduUmassCsGnsclientClientHttpAndroidDownloadTask *create_EduUmassCsGnsclientClientHttpAndroidDownloadTask_init();

J2OBJC_TYPE_LITERAL_HEADER(EduUmassCsGnsclientClientHttpAndroidDownloadTask)

#endif

#pragma pop_macro("INCLUDE_ALL_EduUmassCsGnsclientClientHttpAndroidDownloadTask")
